### ISSUE TITLE
Issues with the deeprenewal package

### ISSUE THREAD

**Issue by OlumideAkinola** [manujosephv/manujosephv#1]
Hi Joseph, 

I am currently working with your open sour library for a forecast for intermittent demand. I would like your help to resolve this issue I come across when I try to import the needed libraries;

from gluonts.dataset.util import to_pandas
from deeprenewal import DeepRenewalEstimator

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [18], in <cell line: 15>()
     13 #from deeprenewal import get_dataset
     14 from gluonts.dataset.util import to_pandas
---> 15 from deeprenewal import DeepRenewalEstimator
     16 '''from deeprenewal import CrostonForecastPredictor
     17 from deeprenewal import IntermittentEvaluator
     18 from gluonts.model.deepar import DeepAREstimator
   (...)
     37 from pathlib import Path
     38 pd.set_option('display.max_columns', 500)'''

File ~/opt/anaconda3/lib/python3.9/site-packages/deeprenewal/__init__.py:8, in <module>
      5 __version__ = '0.3.1'
      7 # Relative imports
----> 8 from .deeprenewal._estimator import DeepRenewalEstimator
      9 from .croston._estimator import CrostonForecastEstimator
     10 from .croston._predictor import CrostonForecastPredictor

File ~/opt/anaconda3/lib/python3.9/site-packages/deeprenewal/deeprenewal/_estimator.py:8, in <module>
      5 import numpy as np
      7 # First-party imports
----> 8 from gluonts.core.component import DType, validated
      9 from gluonts.dataset.field_names import FieldName
     10 from gluonts.distribution import DistributionOutput, NegativeBinomialOutput

ImportError: cannot import name 'DType' from 'gluonts.core.component' (/Users/Olumide.Akinola/opt/anaconda3/lib/python3.9/site-packages/gluonts/core/component.py)

**Comment by manujosephv** [comment]
Firstly - This is not a repository. This is just the repo of my Profile page :) 

And secondly, the deeprenewal package is out of date and not supported anymore. The official GluonTS library supports this model (Deep Renewal Processes) right now and is actively supported. I suggest you try that.

Closing the issue for now.
